version: '3.3'

services:
  bot:
    image: "bot"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/bot"
    volumes:
      - .:/usr/src/app/bot
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"

    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    environment:
      - NGROK_CONFIG=/etc/ngrok.yml
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
  # api:
  #   image: "api"
  #   stop_signal: SIGINT
  #   build:
  #     context: .
  #     dockerfile: infrastructure/api/Dockerfile
  #   working_dir: "/usr/src/app/api"
  #   volumes:
  #     - .:/usr/src/app/api
  #   command:
  #     [
  #       "uvicorn",
  #       "infrastructure.api.app:app",
  #       "--host",
  #       "0.0.0.0",
  #       "--port",
  #       "8000"
  #     ]
  #   restart: always
  #   env_file:
  #     - ".env"
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "200k"
  #       max-file: "10"
